import Darwin
import Foundation

public enum XrayLogLevel: String, Codable, CaseIterable, Sendable {
    case none
    case error
    case warning
    case info
    case debug

    public var displayName: String {
        switch self {
        case .none: "关闭"
        case .error: "仅错误"
        case .warning: "警告"
        case .info: "信息"
        case .debug: "调试"
        }
    }
}

/// Determines how traffic entering the local mixed proxy is routed.
///
/// The values intentionally match the names used by common proxy clients so
/// that the setting is easy to understand when inspecting the JSON file, but
/// the actual routing is generated by ViaSix's Xray configuration builder.
public enum ProxyRoutingMode: String, Codable, CaseIterable, Sendable {
    case rule
    case global
    case direct

    public var displayName: String {
        switch self {
        case .rule: "规则"
        case .global: "全局"
        case .direct: "直连"
        }
    }

    /// Accept a few human-authored aliases while keeping the persisted
    /// representation canonical (`rule`, `global`, or `direct`).
    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let value = try container.decode(String.self)
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
        switch value {
        case "rule", "rules", "rule-based", "规则":
            self = .rule
        case "global", "全局":
            self = .global
        case "direct", "直连":
            self = .direct
        default:
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "Unsupported proxy routing mode: \(value)"
            )
        }
    }
}

public enum LocalProxyConfigurationError: LocalizedError, Equatable, Sendable {
    case invalidListenAddress
    case invalidPort

    public var errorDescription: String? {
        switch self {
        case .invalidListenAddress:
            "本地监听地址必须是 127.0.0.0/8、::1 或 localhost"
        case .invalidPort:
            "本地监听端口必须在 1–65535 之间"
        }
    }
}

public struct LocalProxyConfiguration: Codable, Equatable, Sendable {
    public var listenAddress: String
    public var port: Int
    public var udpEnabled: Bool
    public var sniffingEnabled: Bool
    public var bypassPrivateNetworks: Bool
    public var logLevel: XrayLogLevel
    public var routingMode: ProxyRoutingMode
    /// Whether ViaSix should publish the local mixed proxy through macOS while
    /// Xray is running. The operating-system state itself is managed
    /// transactionally and is never treated as server configuration.
    public var systemProxyEnabled: Bool

    public init(
        listenAddress: String = AppMetadata.proxyHost,
        port: Int = AppMetadata.proxyPort,
        udpEnabled: Bool = true,
        sniffingEnabled: Bool = true,
        bypassPrivateNetworks: Bool = true,
        logLevel: XrayLogLevel = .warning,
        routingMode: ProxyRoutingMode = .rule,
        systemProxyEnabled: Bool = false
    ) {
        self.listenAddress = listenAddress
        self.port = port
        self.udpEnabled = udpEnabled
        self.sniffingEnabled = sniffingEnabled
        self.bypassPrivateNetworks = bypassPrivateNetworks
        self.logLevel = logLevel
        self.routingMode = routingMode
        self.systemProxyEnabled = systemProxyEnabled
    }

    public static let `default` = Self()

    private enum CodingKeys: String, CodingKey {
        case listenAddress
        case port
        case udpEnabled
        case sniffingEnabled
        case bypassPrivateNetworks
        case logLevel
        case routingMode
        case systemProxyEnabled
    }

    /// Decode older local-proxy files that predate `routingMode`. Every
    /// property has a safe default so partially written or hand-authored
    /// settings remain readable and are normalized by `validated()`.
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        listenAddress =
            try container.decodeIfPresent(String.self, forKey: .listenAddress)
            ?? AppMetadata.proxyHost
        port =
            try container.decodeIfPresent(Int.self, forKey: .port)
            ?? AppMetadata.proxyPort
        udpEnabled =
            try container.decodeIfPresent(Bool.self, forKey: .udpEnabled)
            ?? true
        sniffingEnabled =
            try container.decodeIfPresent(Bool.self, forKey: .sniffingEnabled)
            ?? true
        bypassPrivateNetworks =
            try container.decodeIfPresent(Bool.self, forKey: .bypassPrivateNetworks)
            ?? true
        logLevel =
            try container.decodeIfPresent(XrayLogLevel.self, forKey: .logLevel)
            ?? .warning
        routingMode =
            try container.decodeIfPresent(ProxyRoutingMode.self, forKey: .routingMode)
            ?? .rule
        systemProxyEnabled =
            try container.decodeIfPresent(Bool.self, forKey: .systemProxyEnabled)
            ?? false
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(listenAddress, forKey: .listenAddress)
        try container.encode(port, forKey: .port)
        try container.encode(udpEnabled, forKey: .udpEnabled)
        try container.encode(sniffingEnabled, forKey: .sniffingEnabled)
        try container.encode(bypassPrivateNetworks, forKey: .bypassPrivateNetworks)
        try container.encode(logLevel, forKey: .logLevel)
        try container.encode(routingMode, forKey: .routingMode)
        try container.encode(systemProxyEnabled, forKey: .systemProxyEnabled)
    }

    public func validated() throws -> LocalProxyConfiguration {
        var copy = self
        copy.listenAddress = copy.listenAddress.trimmingCharacters(in: .whitespacesAndNewlines)
            .lowercased()
        guard Self.isLoopbackHost(copy.listenAddress) else {
            throw LocalProxyConfigurationError.invalidListenAddress
        }
        guard (1...65_535).contains(copy.port) else {
            throw LocalProxyConfigurationError.invalidPort
        }
        return copy
    }

    public var endpoint: ProxyEndpoint {
        ProxyEndpoint(host: listenAddress, port: port)
    }

    static func isLoopbackHost(_ value: String) -> Bool {
        let host = value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if host == "localhost" || host == "::1" { return true }

        var address = in_addr()
        let isIPv4 = host.withCString { inet_pton(AF_INET, $0, &address) == 1 }
        guard isIPv4 else { return false }
        return (UInt32(bigEndian: address.s_addr) >> 24) == 127
    }
}

extension JSONEncoder {
    static var pretty: JSONEncoder {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        return encoder
    }
}
