//! Mihomo runtime projection aligned with monorepo `contracts/fixtures`.

use serde_yaml::{Mapping, Value};
use std::net::Ipv6Addr;
use std::str::FromStr;
use thiserror::Error;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RoutingMode {
    Rule,
    Global,
    Direct,
}

impl RoutingMode {
    pub fn parse(raw: &str) -> Option<Self> {
        match raw {
            "rule" => Some(Self::Rule),
            "global" => Some(Self::Global),
            "direct" => Some(Self::Direct),
            _ => None,
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Self::Rule => "rule",
            Self::Global => "global",
            Self::Direct => "direct",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProjectionKind {
    User,
    PrivilegedTun,
}

impl ProjectionKind {
    #[cfg(test)]
    pub fn parse(raw: &str) -> Option<Self> {
        match raw {
            "user" => Some(Self::User),
            "privilegedTun" => Some(Self::PrivilegedTun),
            _ => None,
        }
    }
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum ProjectError {
    #[error("selectedNodeMustBeIPv6")]
    SelectedNodeMustBeIPv6,
    #[error("ipv6ManagedProfileRequired")]
    Ipv6ManagedProfileRequired,
    #[error("missingTunConfiguration")]
    MissingTunConfiguration,
    #[error("invalidYAML: {0}")]
    InvalidYaml(String),
    #[error("topLevelMustBeMapping")]
    TopLevelMustBeMapping,
}

impl ProjectError {
    pub fn contract_code(&self) -> &'static str {
        match self {
            Self::SelectedNodeMustBeIPv6 => "selectedNodeMustBeIPv6",
            Self::Ipv6ManagedProfileRequired => "ipv6ManagedProfileRequired",
            Self::MissingTunConfiguration => "missingTunConfiguration",
            Self::InvalidYaml(_) => "invalidYAML",
            Self::TopLevelMustBeMapping => "topLevelMustBeMapping",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ProjectOptions {
    pub routing_mode: RoutingMode,
    pub projection: ProjectionKind,
    pub selected_address: Option<String>,
    pub listen_address: String,
    pub mixed_port: u16,
    pub log_level: String,
    pub ipv6_enabled: bool,
    pub udp_enabled: bool,
    pub sniffing_enabled: bool,
}

impl Default for ProjectOptions {
    fn default() -> Self {
        Self {
            routing_mode: RoutingMode::Rule,
            projection: ProjectionKind::User,
            selected_address: None,
            listen_address: "127.0.0.1".into(),
            mixed_port: 11_451,
            log_level: "info".into(),
            ipv6_enabled: true,
            udp_enabled: true,
            sniffing_enabled: true,
        }
    }
}

/// Project a user profile into a Mihomo runtime configuration mapping.
pub fn project_runtime(
    profile_yaml: Option<&str>,
    options: &ProjectOptions,
) -> Result<Mapping, ProjectError> {
    if options.projection == ProjectionKind::PrivilegedTun {
        // Windows MVP ships user-space only; keep the error code for contracts.
        return Err(ProjectError::MissingTunConfiguration);
    }

    let mut runtime = base_runtime(options);

    if options.routing_mode == RoutingMode::Direct {
        runtime.insert(Value::from("rules"), Value::Sequence(vec![Value::from("MATCH,DIRECT")]));
        runtime.insert(
            Value::from("tun"),
            Value::Mapping(mapping([("enable", Value::Bool(false))])),
        );
        return Ok(runtime);
    }

    let profile_yaml = profile_yaml
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or(ProjectError::Ipv6ManagedProfileRequired)?;

    let root = parse_mapping(profile_yaml)?;
    let selected = resolve_selected_address(options.selected_address.as_deref())?;
    let mut proxy = extract_primary_proxy(&root, &selected)?;
    let allows_udp = proxy
        .get(Value::from("udp"))
        .and_then(Value::as_bool)
        .unwrap_or(true);
    proxy.insert(
        Value::from("udp"),
        Value::Bool(options.udp_enabled && allows_udp),
    );

    runtime.insert(
        Value::from("proxies"),
        Value::Sequence(vec![Value::Mapping(proxy.clone())]),
    );

    if options.sniffing_enabled {
        runtime.insert(Value::from("sniffer"), sniffer_mapping());
    }

    install_routing_policy(&mut runtime, options.routing_mode, &proxy)?;

    runtime.insert(
        Value::from("tun"),
        Value::Mapping(mapping([("enable", Value::Bool(false))])),
    );

    // Explicitly ensure stripped keys are absent even if somehow present.
    for key in [
        "proxy-providers",
        "proxy-groups",
        "rule-providers",
        "sub-rules",
        "x-viasix",
    ] {
        runtime.remove(Value::from(key));
    }

    Ok(runtime)
}

pub fn project_runtime_yaml(
    profile_yaml: Option<&str>,
    options: &ProjectOptions,
) -> Result<String, ProjectError> {
    let mapping = project_runtime(profile_yaml, options)?;
    let mut out = String::from("# Generated by ViaSix for Mihomo\n");
    let body = serde_yaml::to_string(&Value::Mapping(mapping))
        .map_err(|e| ProjectError::InvalidYaml(e.to_string()))?;
    out.push_str(&body);
    if !out.ends_with('\n') {
        out.push('\n');
    }
    Ok(out)
}

fn base_runtime(options: &ProjectOptions) -> Mapping {
    let mut profile = Mapping::new();
    profile.insert(Value::from("store-selected"), Value::Bool(false));
    profile.insert(Value::from("store-fake-ip"), Value::Bool(false));

    mapping([
        ("mixed-port", Value::from(options.mixed_port as i64)),
        ("allow-lan", Value::Bool(false)),
        ("bind-address", Value::from(options.listen_address.as_str())),
        ("mode", Value::from(options.routing_mode.as_str())),
        ("log-level", Value::from(options.log_level.as_str())),
        ("ipv6", Value::Bool(options.ipv6_enabled)),
        ("unified-delay", Value::Bool(true)),
        ("tcp-concurrent", Value::Bool(true)),
        ("profile", Value::Mapping(profile)),
    ])
}

fn parse_mapping(yaml: &str) -> Result<Mapping, ProjectError> {
    let value: Value =
        serde_yaml::from_str(yaml).map_err(|e| ProjectError::InvalidYaml(e.to_string()))?;
    match value {
        Value::Mapping(m) => Ok(m),
        Value::Null => Ok(Mapping::new()),
        _ => Err(ProjectError::TopLevelMustBeMapping),
    }
}

fn resolve_selected_address(selected: Option<&str>) -> Result<String, ProjectError> {
    let Some(raw) = selected.map(str::trim).filter(|s| !s.is_empty()) else {
        return Err(ProjectError::SelectedNodeMustBeIPv6);
    };
    if Ipv6Addr::from_str(raw).is_err() {
        return Err(ProjectError::SelectedNodeMustBeIPv6);
    }
    Ok(raw.to_string())
}

fn extract_primary_proxy(root: &Mapping, selected: &str) -> Result<Mapping, ProjectError> {
    let proxies = root
        .get(Value::from("proxies"))
        .and_then(Value::as_sequence)
        .ok_or(ProjectError::Ipv6ManagedProfileRequired)?;

    let index = primary_server_index(root, proxies)
        .ok_or(ProjectError::Ipv6ManagedProfileRequired)?;

    let Value::Mapping(mut proxy) = proxies[index].clone() else {
        return Err(ProjectError::Ipv6ManagedProfileRequired);
    };

    let name = proxy
        .get(Value::from("name"))
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty());
    let ty = proxy
        .get(Value::from("type"))
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|s| !s.is_empty());
    if name.is_none() || ty.is_none() {
        return Err(ProjectError::Ipv6ManagedProfileRequired);
    }

    proxy.insert(Value::from("server"), Value::from(selected));
    Ok(proxy)
}

fn primary_server_index(root: &Mapping, proxies: &[Value]) -> Option<usize> {
    if let Some(idx) = proxies.iter().position(|proxy| {
        proxy
            .as_mapping()
            .and_then(|m| m.get(Value::from("server")))
            .and_then(Value::as_str)
            .map(|s| !s.trim().is_empty())
            .unwrap_or(false)
    }) {
        return Some(idx);
    }

    let selected_ip = root
        .get(Value::from("x-viasix"))
        .and_then(Value::as_mapping)
        .and_then(|m| m.get(Value::from("primary-server")))
        .and_then(Value::as_str)
        == Some("selected-ip");

    if !selected_ip {
        return None;
    }

    proxies.iter().position(|proxy| {
        let ty = proxy
            .as_mapping()
            .and_then(|m| m.get(Value::from("type")))
            .and_then(Value::as_str)
            .map(|s| s.to_ascii_lowercase())
            .unwrap_or_default();
        !matches!(ty.as_str(), "direct" | "reject" | "dns")
    })
}

fn install_routing_policy(
    runtime: &mut Mapping,
    mode: RoutingMode,
    primary: &Mapping,
) -> Result<(), ProjectError> {
    match mode {
        RoutingMode::Direct => {
            runtime.remove(Value::from("proxies"));
            runtime.insert(
                Value::from("rules"),
                Value::Sequence(vec![Value::from("MATCH,DIRECT")]),
            );
        }
        RoutingMode::Global => {
            runtime.remove(Value::from("rules"));
        }
        RoutingMode::Rule => {
            let target = primary
                .get(Value::from("name"))
                .and_then(Value::as_str)
                .map(str::trim)
                .filter(|s| !s.is_empty())
                .ok_or(ProjectError::Ipv6ManagedProfileRequired)?;
            let rules = vec![
                "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve",
                "IP-CIDR,100.64.0.0/10,DIRECT,no-resolve",
                "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve",
                "IP-CIDR,169.254.0.0/16,DIRECT,no-resolve",
                "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve",
                "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve",
                "IP-CIDR6,::1/128,DIRECT,no-resolve",
                "IP-CIDR6,fc00::/7,DIRECT,no-resolve",
                "IP-CIDR6,fe80::/10,DIRECT,no-resolve",
            ]
            .into_iter()
            .map(Value::from)
            .chain(std::iter::once(Value::from(format!("MATCH,{target}"))))
            .collect::<Vec<_>>();
            runtime.insert(Value::from("rules"), Value::Sequence(rules));
        }
    }
    Ok(())
}

fn sniffer_mapping() -> Value {
    Value::Mapping(mapping([
        ("enable", Value::Bool(true)),
        ("force-dns-mapping", Value::Bool(true)),
        ("parse-pure-ip", Value::Bool(true)),
        ("override-destination", Value::Bool(true)),
        (
            "sniff",
            Value::Mapping(mapping([
                (
                    "HTTP",
                    Value::Mapping(mapping([
                        (
                            "ports",
                            Value::Sequence(vec![Value::from("80"), Value::from("8080-8880")]),
                        ),
                        ("override-destination", Value::Bool(true)),
                    ])),
                ),
                (
                    "TLS",
                    Value::Mapping(mapping([(
                        "ports",
                        Value::Sequence(vec![Value::from("443"), Value::from("8443")]),
                    )])),
                ),
                (
                    "QUIC",
                    Value::Mapping(mapping([(
                        "ports",
                        Value::Sequence(vec![Value::from("443"), Value::from("8443")]),
                    )])),
                ),
            ])),
        ),
    ]))
}

fn mapping<const N: usize>(entries: [(&str, Value); N]) -> Mapping {
    let mut map = Mapping::new();
    for (k, v) in entries {
        map.insert(Value::from(k), v);
    }
    map
}

#[cfg(test)]
mod contract_tests {
    use super::*;
    use serde::Deserialize;
    use serde_yaml::Value;
    use std::fs;
    use std::path::{Path, PathBuf};

    #[derive(Debug, Deserialize)]
    struct CaseFile {
        id: String,
        #[serde(rename = "selectedAddress")]
        selected_address: Option<String>,
        #[serde(rename = "routingMode")]
        routing_mode: String,
        projection: String,
        #[serde(rename = "requireProfile")]
        require_profile: Option<bool>,
        expect: Expect,
    }

    #[derive(Debug, Deserialize)]
    struct Expect {
        success: bool,
        #[serde(rename = "errorCode")]
        error_code: Option<String>,
        mode: Option<String>,
        #[serde(rename = "proxyCount")]
        proxy_count: Option<usize>,
        #[serde(rename = "primaryProxyName")]
        primary_proxy_name: Option<String>,
        #[serde(rename = "primaryProxyServer")]
        primary_proxy_server: Option<String>,
        #[serde(rename = "absentKeys")]
        absent_keys: Option<Vec<String>>,
        #[serde(rename = "lastRule")]
        last_rule: Option<String>,
        #[serde(rename = "rulesMustContain")]
        rules_must_contain: Option<Vec<String>>,
        #[serde(rename = "rulesExact")]
        rules_exact: Option<Vec<String>>,
        #[serde(rename = "tunEnable")]
        tun_enable: Option<bool>,
    }

    fn monorepo_root() -> PathBuf {
        let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        for _ in 0..8 {
            if dir.join("contracts/VERSION").is_file() {
                return dir;
            }
            if !dir.pop() {
                break;
            }
        }
        panic!("contracts/VERSION not found from {}", env!("CARGO_MANIFEST_DIR"));
    }

    #[test]
    fn all_contract_projection_cases() {
        let cases_dir = monorepo_root().join("contracts/fixtures/mihomo-config/cases");
        let mut names: Vec<_> = fs::read_dir(&cases_dir)
            .expect("cases dir")
            .filter_map(|e| e.ok())
            .filter(|e| e.path().is_dir())
            .map(|e| e.file_name().to_string_lossy().into_owned())
            .collect();
        names.sort();
        assert!(!names.is_empty(), "no contract cases");

        for name in names {
            let case_dir = cases_dir.join(&name);
            run_case(&case_dir);
        }
    }

    fn run_case(case_dir: &Path) {
        let case: CaseFile = serde_json::from_str(
            &fs::read_to_string(case_dir.join("case.json")).expect("case.json"),
        )
        .expect("decode case.json");
        let input = fs::read_to_string(case_dir.join("input.yaml")).expect("input.yaml");

        let mut options = ProjectOptions::default();
        options.routing_mode =
            RoutingMode::parse(&case.routing_mode).expect("routingMode");
        options.projection = ProjectionKind::parse(&case.projection).expect("projection");
        options.selected_address = case.selected_address.clone();

        let profile = if case.require_profile == Some(false) {
            None
        } else {
            Some(input.as_str())
        };

        match project_runtime(profile, &options) {
            Ok(root) => {
                assert!(
                    case.expect.success,
                    "case {} expected failure but succeeded",
                    case.id
                );
                assert_success(&case.id, &root, &case.expect);
            }
            Err(err) => {
                assert!(
                    !case.expect.success,
                    "case {} unexpected error: {}",
                    case.id,
                    err
                );
                assert_eq!(
                    Some(err.contract_code().to_string()),
                    case.expect.error_code,
                    "case {} error code",
                    case.id
                );
            }
        }
    }

    fn assert_success(id: &str, root: &Mapping, expect: &Expect) {
        if let Some(mode) = &expect.mode {
            assert_eq!(
                root.get(Value::from("mode")).and_then(Value::as_str),
                Some(mode.as_str()),
                "{id}: mode"
            );
        }

        let proxies = root
            .get(Value::from("proxies"))
            .and_then(Value::as_sequence)
            .cloned()
            .unwrap_or_default();
        if let Some(count) = expect.proxy_count {
            assert_eq!(proxies.len(), count, "{id}: proxyCount");
        }
        let primary = proxies.first().and_then(Value::as_mapping);
        if let Some(name) = &expect.primary_proxy_name {
            assert_eq!(
                primary
                    .and_then(|m| m.get(Value::from("name")))
                    .and_then(Value::as_str),
                Some(name.as_str()),
                "{id}: primaryProxyName"
            );
        }
        if let Some(server) = &expect.primary_proxy_server {
            assert_eq!(
                primary
                    .and_then(|m| m.get(Value::from("server")))
                    .and_then(Value::as_str),
                Some(server.as_str()),
                "{id}: primaryProxyServer"
            );
        }

        for key in expect.absent_keys.iter().flatten() {
            assert!(
                !root.contains_key(Value::from(key.as_str())),
                "{id}: expected absent {key}"
            );
        }

        let rules: Vec<String> = root
            .get(Value::from("rules"))
            .and_then(Value::as_sequence)
            .map(|seq| {
                seq.iter()
                    .filter_map(Value::as_str)
                    .map(str::to_string)
                    .collect()
            })
            .unwrap_or_default();

        if let Some(last) = &expect.last_rule {
            assert_eq!(rules.last().map(String::as_str), Some(last.as_str()), "{id}: lastRule");
        }
        for rule in expect.rules_must_contain.iter().flatten() {
            assert!(rules.contains(rule), "{id}: missing rule {rule} in {rules:?}");
        }
        if let Some(exact) = &expect.rules_exact {
            assert_eq!(&rules, exact, "{id}: rulesExact");
        }

        if let Some(tun_enable) = expect.tun_enable {
            let actual = root
                .get(Value::from("tun"))
                .and_then(Value::as_mapping)
                .and_then(|m| m.get(Value::from("enable")))
                .and_then(Value::as_bool);
            assert_eq!(actual, Some(tun_enable), "{id}: tunEnable");
        }
    }
}
